### ISSUE TITLE
Frame issue

### ISSUE THREAD

**Issue by reaper666735** [ascott18/ImprovedLootFrame#1]
only just noticed you have a Github page :p, 

in case you have not checked curse.com il just copy the issue:

when you try to loot while in combat (or get into aggro when you get near to click the corpse) the loot frame does not show up and misses loot sometimes... , all i get is the "Interface action failed because of a AddOn" message in chat,

i tested it again with the addon disabled and i can see the frame again (in combat or when aggro'd) it might be linked to the old message from the Taint log below that i posted awhile ago i'm not sure, since i have no real "error" to post,

a random look in my taintlog:

7/20 19:07:26.871 Execution tainted by ImprovedLootFrame while reading LOOTFRAME_AUTOLOOT_DELAY - Interface\FrameXML\LootFrame.lua:62

7/20 19:07:26.871 Execution tainted by ImprovedLootFrame while reading LootFrame_Show - Interface\FrameXML\LootFrame.lua:69

**Comment by ascott18** [comment]
Somehow missed this - this should have been fixed quite some time ago.
